// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdEs_TW_bCCl8Y_Cn-OqApJVyFSCYdCs4',
    appId: '1:787651827255:web:f77e650d429963477e91b2',
    messagingSenderId: '787651827255',
    projectId: 'rihla-fe9aa',
    authDomain: 'rihla-fe9aa.firebaseapp.com',
    databaseURL: 'https://rihla-fe9aa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rihla-fe9aa.appspot.com',
    measurementId: 'G-XHBHER8E82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADDO5zcf0L-xsabPWNYzOhwDEfjMXK84o',
    appId: '1:787651827255:android:b7c52c49fda2d12f7e91b2',
    messagingSenderId: '787651827255',
    projectId: 'rihla-fe9aa',
    databaseURL: 'https://rihla-fe9aa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rihla-fe9aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV0ylvr_z6gZKLVl61xSOiTjXOfMKPH9o',
    appId: '1:787651827255:ios:bcc9fed5c3d7972a7e91b2',
    messagingSenderId: '787651827255',
    projectId: 'rihla-fe9aa',
    databaseURL: 'https://rihla-fe9aa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rihla-fe9aa.appspot.com',
    iosBundleId: 'com.example.rihla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV0ylvr_z6gZKLVl61xSOiTjXOfMKPH9o',
    appId: '1:787651827255:ios:bcc9fed5c3d7972a7e91b2',
    messagingSenderId: '787651827255',
    projectId: 'rihla-fe9aa',
    databaseURL: 'https://rihla-fe9aa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rihla-fe9aa.appspot.com',
    iosBundleId: 'com.example.rihla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdEs_TW_bCCl8Y_Cn-OqApJVyFSCYdCs4',
    appId: '1:787651827255:web:614babc0434f0de47e91b2',
    messagingSenderId: '787651827255',
    projectId: 'rihla-fe9aa',
    authDomain: 'rihla-fe9aa.firebaseapp.com',
    databaseURL: 'https://rihla-fe9aa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rihla-fe9aa.appspot.com',
    measurementId: 'G-QXKZW72X2V',
  );
}
