// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3eUwojHEcKwEMU5r4xtw0F5IHoMacPYo',
    appId: '1:352323073281:web:e0cadacefc19e005cc5700',
    messagingSenderId: '352323073281',
    projectId: 'rihla-db4be',
    authDomain: 'rihla-db4be.firebaseapp.com',
    storageBucket: 'rihla-db4be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJnGalKT4e-bMbMweQ76Gb1BZAy15uiI',
    appId: '1:352323073281:android:cebd77cc9be522f0cc5700',
    messagingSenderId: '352323073281',
    projectId: 'rihla-db4be',
    storageBucket: 'rihla-db4be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpVBhS7tDGjjuFug3RuM_9PZUJCGwmEoE',
    appId: '1:352323073281:ios:e38ebbd2646fca87cc5700',
    messagingSenderId: '352323073281',
    projectId: 'rihla-db4be',
    storageBucket: 'rihla-db4be.appspot.com',
    iosBundleId: 'com.example.rihla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpVBhS7tDGjjuFug3RuM_9PZUJCGwmEoE',
    appId: '1:352323073281:ios:e38ebbd2646fca87cc5700',
    messagingSenderId: '352323073281',
    projectId: 'rihla-db4be',
    storageBucket: 'rihla-db4be.appspot.com',
    iosBundleId: 'com.example.rihla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3eUwojHEcKwEMU5r4xtw0F5IHoMacPYo',
    appId: '1:352323073281:web:68de3b559ed47180cc5700',
    messagingSenderId: '352323073281',
    projectId: 'rihla-db4be',
    authDomain: 'rihla-db4be.firebaseapp.com',
    storageBucket: 'rihla-db4be.appspot.com',
  );

}